version: '2'
services:
  collectd:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_HOST: fake_sfx
    depends_on:
      - fake_sfx
      - etcd238
      - etcd310
      - etcd324

  etcd238:
    image: quay.io/coreos/etcd:v2.3.8
    ports:
      - 2379
    command: >
      --name
      etcd238
      -advertise-client-urls
      http://etcd238:2379
      -listen-client-urls
      http://0.0.0.0:2379
      -initial-advertise-peer-urls
      http://etcd238:2380
      -listen-peer-urls
      http://0.0.0.0:2380
      -initial-cluster
      etcd238=http://etcd238:2380

  etcd310:
    image: quay.io/coreos/etcd:v3.1.0
    ports:
      - 2379
    command: >
      etcd --name
      etcd310
      -advertise-client-urls
      http://etcd310:2379
      -listen-client-urls
      http://0.0.0.0:2379
      -initial-advertise-peer-urls
      http://etcd310:2380
      -listen-peer-urls
      http://0.0.0.0:2380
      -initial-cluster
      etcd310=http://etcd310:2380

  etcd324:
    image: quay.io/coreos/etcd:v3.2
    ports:
      - 2379
    command: >
      etcd --name
      etcd324
      -advertise-client-urls
      http://etcd324:2379
      -listen-client-urls
      http://0.0.0.0:2379
      -initial-advertise-peer-urls
      http://etcd324:2380
      -listen-peer-urls
      http://0.0.0.0:2380
      -initial-cluster
      etcd324=http://etcd324:2380

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectd
